### ISSUE TITLE
Session hijack potential

### ISSUE THREAD

**Issue by ghost** [hazelcast/hazelcast-wm#1]
If access is made with a `JSESSIONID` and `hazelcast.sessionId` pairing, it is not validated that these are associated with each other. This gives the potential to access someone else's session.

**Comment by emre-aydin** [comment]
@ghost This potential is not different from someone knowing your `JSESSIONID` and doesn't cause any more possibilities for potential access to someone else's session. To make your `hazelcast.sessionId` cookie more secure, you can do the following:

1. Use a secure transport
2. Set `cookie-secure` to `true` for Hazelcast's `WebFilter` for enforcing a secure transport
3. Set `cookie-http-only` to `true` for the `WebFilter` in order to protect the cookie from scripting

You can find more information on how to configure Hazelcast's `WebFilter` [here](https://github.com/hazelcast/hazelcast-wm#setting-up-session-clustering)
