### ISSUE TITLE
request.getSession() returns null

### ISSUE THREAD

**Issue by anton-johansson** [hazelcast/hazelcast-wm#32]
`HttpServletRequest#getSession()`. The JavaDoc says:

> Returns the current session associated with this request, or if the request does not have a session, creates one.

To me it feels like this method should never return `null`. The Hazelcast wrapped `HttpServletRequest` returns `null` if the request is committed, according to this code:
```java
if (hazelcastSession == null && !res.isCommitted() && (create || hazelcastSessionId != null)) {
    hazelcastSession = createNewSession(HazelcastRequestWrapper.this, hazelcastSessionId);
}
```

I have a custom filter that does some different kinds of logging. It includes `request.getSession().getId()`. This gives me an NPE if the request is committed, which happens sometimes out of my control.

For now I'll just wrap this in a null check, but maybe it's something that should be fixed?

**Comment by emre-aydin** [comment]
@anton-johansson,

If response is committed, a new session cannot be created (or you'll get an `IllegalStateException`). JavaDoc doesn't make it sound like that, but `null` can be returned from `getSession` method and it should in this case.

Committing the response means writing response headers to client and in order to create a session, you need to tell the client to set a cookie with the session ID. In this case, as you have already sent the headers to client, there's no way you can create a session after that point.

**Comment by anton-johansson** [comment]
Aha, okay. My bad, thanks for the clarification!
